# Generated by Django 4.0.7 on 2022-08-25 19:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_use_json_field_for_body_streamfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="promo_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Write some promotional copy",
                max_length=1000,
                null=True,
            ),
        ),
    ]
