# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreadsLandingPage',
            new_name='BreadsIndexPage',
        ),
    ]
