# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0002_auto_20170217_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadsindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Listing image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
