# Generated by Django 2.2.9 on 2020-01-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image'),
        ),
        migrations.AlterField(
            model_name='breadsindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image'),
        ),
    ]
