# Generated by Django 3.1.6 on 2021-02-26 06:21

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0004_bootstrap_translatable_mixin'),
    ]

    operations = [
        BootstrapTranslatableModel('breads.Country'),
        BootstrapTranslatableModel('breads.BreadIngredient'),
        BootstrapTranslatableModel('breads.BreadType'),
    ]
