# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0005_auto_20170224_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadpage',
            name='body',
        ),
    ]
