# Generated by Django 4.2.7 on 2024-02-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0006_breadingredient_expire_at_breadingredient_expired_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "verbose_name": "Country of Origin",
                "verbose_name_plural": "Countries of Origin",
            },
        ),
    ]
