# Generated by Django 5.1.dev20240316121317 on 2024-04-23 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("breads", "0006_breadingredient_expire_at_breadingredient_expired_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breadingredient",
            options={
                "verbose_name": "bread ingredient",
                "verbose_name_plural": "bread ingredients",
            },
        ),
        migrations.AlterModelOptions(
            name="breadtype",
            options={
                "verbose_name": "bread type",
                "verbose_name_plural": "bread types",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "verbose_name": "country of origin",
                "verbose_name_plural": "countries of origin",
            },
        ),
    ]
