# Generated by Django 4.0.10 on 2023-08-29 08:49

import bakerydemo.dataverse.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0006_breadingredient_expire_at_breadingredient_expired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breadpage",
            name="other_audiences",
            field=bakerydemo.dataverse.fields.DataverseMultipleReferenceField(
                default=list,
                label_column="cr50c_name",
                pk_column="cr50c_newtableid",
                table_id="cr50c_newtables",
                verbose_name="other audiences",
            ),
        ),
        migrations.AddField(
            model_name="breadpage",
            name="primary_audience",
            field=bakerydemo.dataverse.fields.DataverseReferenceField(
                default="",
                label_column="cr50c_name",
                max_length=36,
                pk_column="cr50c_newtableid",
                table_id="cr50c_newtables",
                verbose_name="primary audience",
            ),
            preserve_default=False,
        ),
    ]
