# Generated by Django 5.2.7 on 2025-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0009_alter_breadpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breadingredient",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "bread ingredient",
                "verbose_name_plural": "bread ingredients",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "verbose_name": "country of origin",
                "verbose_name_plural": "countries of origin",
            },
        ),
        migrations.AddField(
            model_name="breadingredient",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="sort_order",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
