# Generated by Django 6.0.9 on 2026-10-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0010_alter_breadingredient_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
