# Generated by Django 5.2.7 on 2025-10-27 08:12

from django.db import migrations


def backfill_country_sort_order(apps, schema_editor):
    """
    Backfill sort_order for existing Country instances.
    Assigns sort_order based on alphabetical order of title.
    """
    Country = apps.get_model("breads", "Country")
    for index, country in enumerate(Country.objects.order_by("title"), start=1):
        country.sort_order = index * 10  # Use increments of 10 for flexibility
        country.save(update_fields=["sort_order"])


def backfill_ingredient_sort_order(apps, schema_editor):
    """
    Backfill sort_order for existing BreadIngredient instances.
    Assigns sort_order based on alphabetical order of name.
    """
    BreadIngredient = apps.get_model("breads", "BreadIngredient")
    for index, ingredient in enumerate(
        BreadIngredient.objects.order_by("name"), start=1
    ):
        ingredient.sort_order = index * 10  # Use increments of 10 for flexibility
        ingredient.save(update_fields=["sort_order"])


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration: set all sort_order values back to None.
    """
    Country = apps.get_model("breads", "Country")
    Country.objects.update(sort_order=None)

    BreadIngredient = apps.get_model("breads", "BreadIngredient")
    BreadIngredient.objects.update(sort_order=None)


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0010_alter_breadingredient_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_country_sort_order, reverse_backfill),
        migrations.RunPython(backfill_ingredient_sort_order, migrations.RunPython.noop),
    ]
