# Generated by Django 6.0.9 on 2026-10-07 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0011_alter_country_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breadingredient",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
