# Generated by Django 5.2.7 on 2025-11-06 13:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
                ('image', models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'People Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('role', models.CharField(help_text='e.g. Lead Developer, Designer, Community Manager', max_length=255, verbose_name='Role/Job Title')),
                ('introduction', models.TextField(blank=True, help_text='Brief introduction or tagline')),
                ('body', wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('block_quote', 12), ('embed_block', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlight')], 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large')], 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('theme', 9), ('text_size', 10)]], {'collapsed': True}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribute_name', 8), ('settings', 11)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {'description': 'An embedded video or other media', 'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'preview_template': 'base/preview/static_embed_block.html', 'preview_value': 'https://www.youtube.com/watch?v=mwrGSfiB1Mg', 'template': 'blocks/embed_block.html'})}, help_text='Full biography with rich content', verbose_name='Biography')),
                ('email', models.EmailField(blank=True, help_text='Public email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Personal website')),
                ('github', models.CharField(blank=True, help_text='GitHub username (without @)', max_length=255, verbose_name='GitHub Username')),
                ('twitter', models.CharField(blank=True, help_text='Twitter handle (without @)', max_length=255, verbose_name='Twitter/X Handle')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=255)),
                ('team', models.CharField(blank=True, choices=[('leadership', 'Leadership'), ('engineering', 'Engineering'), ('design', 'Design'), ('community', 'Community'), ('operations', 'Operations'), ('contributors', 'Contributors')], max_length=100)),
                ('profile_picture', models.ForeignKey(blank=True, help_text='Profile photo - square images work best', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Person Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
