# Generated by Django 5.2.7 on 2025-11-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0009_alter_breadpage_body"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="breads.country",
            ),
        ),
    ]
