# Generated by Django 6.0.3 on 2026-03-06 04:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_personpage_social_links'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Person Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='personpage',
            options={'verbose_name': 'Person Page'},
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='social_links',
        ),
        migrations.AddField(
            model_name='personpage',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='personpage',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personpage',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personpage',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='role',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='PeopleIndexPage',
        ),
    ]
