# Generated by Django 3.2.15 on 2022-09-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_rename_people_person"),
        ("blog", "0005_use_json_field_for_body_streamfield"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPeopleRelationship",
            new_name="BlogPersonRelationship",
        ),
        migrations.RenameField(
            model_name="blogpersonrelationship",
            old_name="people",
            new_name="person",
        ),
    ]
