# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpeoplerelationship',
            old_name='blogpage',
            new_name='page',
        ),
    ]
