# Generated by Django 3.0.8 on 2020-07-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0051_page_locale_fields_notnull'),
        ('blog', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Locale'),
        ),
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
