# Generated by Django 3.0.8 on 2020-08-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0057_page_locale_fields_notnull'),
        ('blog', '0006_i18n_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpeoplerelationship',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='blogpeoplerelationship',
            unique_together={('translation_key', 'locale')},
        ),
    ]
