# Generated by Django 6.0.6 on 2026-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_promo_image_homepage_lead_image_and_more'),
        ('blog', '0008_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blogpersonrelationship',
            constraint=models.UniqueConstraint(fields=('page', 'person'), name='unique_blog_person'),
        ),
    ]
