# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('locations', '0003_auto_20170215_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Location listing image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
