# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locationsindexpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the index page'),
        ),
    ]
