# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20170215_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationoperatinghours',
            name='closed',
            field=models.BooleanField(default='False', help_text='Tick if location is closed', verbose_name='Closed?'),
            preserve_default=False,
        ),
    ]
