# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locationoperatinghours_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationoperatinghours',
            name='closed',
            field=models.BooleanField(help_text='Tick if location is closed on this day', verbose_name='Closed?'),
        ),
        migrations.AlterField(
            model_name='locationoperatinghours',
            name='closing_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='locationoperatinghours',
            name='opening_time',
            field=models.TimeField(blank=True),
        ),
    ]
