# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20170215_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationoperatinghours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationoperatinghours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
