# Generated by Django 4.2.13 on 2024-07-21 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_locationoperatinghours_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationpage",
            name="timezone",
            field=models.TextField(
                default="Etc/UTC",
                help_text="Examples: US/Pacific, America/Los_Angeles, Etc/UTC",
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_tz",
                        message="Examples: US/Pacific, America/Los_Angeles, Etc/UTC",
                        regex="^(\\w+\\/?\\w+)$",
                    )
                ],
            ),
        ),
    ]
