# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20170215_1411'),
        ('locations', '0005_locationsindexpage_introduction'),
    ]

    operations = [
    ]
