# Generated by Django 5.2.7 on 2025-10-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_locationpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOpeningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text="Short description, e.g. 'Holiday hours'", max_length=255)),
                ('special_open_time', models.TimeField(blank=True, null=True)),
                ('special_close_time', models.TimeField(blank=True, null=True)),
                ('operating_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='locations.locationoperatinghours')),
            ],
        ),
    ]
