# Generated by Django 6.0.9 on 2026-10-09 16:45

import uuid

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0008_alter_locationpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationOperatingDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        default="MON",
                        max_length=3,
                    ),
                ),
                (
                    "closed",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Tick if location is closed on this day",
                        verbose_name="Closed?",
                    ),
                ),
                (
                    "location",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours_of_operation",
                        to="locations.locationpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "operating day",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationOperatingTimeSlot",
            fields=[
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                (
                    "day",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="locations.locationoperatingday",
                    ),
                ),
            ],
            options={
                "verbose_name": "time slot",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
