# Generated by Django 5.2.7 on 2025-10-16 13:42

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_specialopeninghour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationoperatinghours',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specialopeninghour',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='specialopeninghour',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='specialopeninghour',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='specialopeninghour',
            name='operating_hour',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='locations.locationoperatinghours'),
        ),
    ]
