# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20170219_0942'),
        ('locations', '0006_auto_20170218_1102'),
    ]

    operations = [
    ]
