# Generated by Django 4.2.13 on 2024-07-26 09:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipepage",
            name="backstory",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 7),
                    ("block_quote", 10),
                    ("embed_block", 11),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow", "template": "blocks/paragraph_block.html"},
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Image is decorative",
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("decorative", 5), ("alt_text", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 8), ("attribute_name", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                },
                help_text="Use only a minimum number of headings and large blocks.",
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("block_quote", 6),
                    ("table_block", 7),
                    ("typed_table_block", 16),
                    ("image_block", 17),
                    ("embed_block", 18),
                    ("ingredients_list", 20),
                    ("steps_list", 23),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {"group": "Content"},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "group": "Content",
                            "icon": "pilcrow",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 4), ("attribute_name", 5)]],
                        {"group": "Content"},
                    ),
                    7: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {"group": "Content"},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {}),
                    9: ("wagtail.blocks.FloatBlock", (), {}),
                    10: ("wagtail.blocks.RichTextBlock", (), {}),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    12: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Image is decorative",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("decorative", 12), ("alt_text", 13)]],
                        {"required": True},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 14), ("caption", 13), ("attribution", 13)]],
                        {},
                    ),
                    16: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [
                            [
                                ("text", 8),
                                ("numeric", 9),
                                ("rich_text", 10),
                                ("image", 15),
                            ]
                        ],
                        {"group": "Content"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 14), ("caption", 13), ("attribution", 13)]],
                        {"group": "Media"},
                    ),
                    18: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "group": "Media",
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {
                            "group": "Cooking",
                            "icon": "list-ol",
                            "max_num": 10,
                            "min_num": 2,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("S", "Small"), ("M", "Medium"), ("L", "Large")]},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 19), ("difficulty", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "group": "Cooking",
                            "icon": "tasks",
                            "max_num": 10,
                            "min_num": 2,
                        },
                    ),
                },
                help_text="The recipe’s step-by-step instructions and any other relevant information.",
            ),
        ),
    ]
