# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='description',
            new_name='introduction',
        ),
    ]
