# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='choices',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
