# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_gallerypage_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='choices',
            field=models.CharField(choices=[(2, 'Something')], max_length=255),
        ),
    ]
