# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170210_1420'),
        ('base', '0004_auto_20170210_1445'),
    ]

    operations = [
    ]
