# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aboutlocationrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Collection'),
        ),
    ]
