# Generated by Django 3.1.6 on 2021-02-26 06:20

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bootstrap_translatable_mixin'),
    ]

    operations = [
        BootstrapTranslatableModel('base.People'),
        BootstrapTranslatableModel('base.FooterText'),
    ]
