# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_merge_20170210_1551'),
        ('base', '0006_auto_20170210_1556'),
    ]

    operations = [
    ]
