# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_homepage'),
        ('base', '0006_auto_20170209_1721'),
    ]

    operations = [
    ]
