# Generated by Django 3.1.2 on 2020-10-05 11:26

from django.contrib.auth.models import User
from django.db import migrations

from wagtail.core.models import Page


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    # Replace any missing owner values
    root_user = User.objects.first()
    for page in Page.objects.filter(owner=None):
        page.owner_id = root_user.pk
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201005_1111'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
