# Generated by Django 4.0.4 on 2022-05-09 08:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_char_field_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
