# Generated by Django 3.0.8 on 2020-08-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0057_page_locale_fields_notnull'),
        ('base', '0008_i18n_3'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='people',
            unique_together={('translation_key', 'locale')},
        ),
    ]
