# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170218_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='choices',
            field=models.ForeignKey(blank=True, help_text='Select the image collection for this gallery.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Collection'),
        ),
    ]
