# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20170220_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerypage',
            old_name='choices',
            new_name='collection',
        ),
    ]
