# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20170222_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutlocationrelationship',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='aboutlocationrelationship',
            name='page',
        ),
        migrations.DeleteModel(
            name='AboutLocationRelationship',
        ),
    ]
