# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20170222_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='header_image',
            new_name='image',
        ),
    ]
