# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170227_2216'),
        ('base', '0013_auto_20170228_0714'),
    ]

    operations = [
    ]
