# Generated by Django 4.2 on 2023-05-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_person_enable_default_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="footertext",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="footertext",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
