# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_merge_20170228_1619'),
        ('base', '0015_auto_20170228_1555'),
    ]

    operations = [
    ]
