# Generated by Django 4.2 on 2023-05-15 10:49

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_footertext_translatable"),
    ]

    operations = [
        BootstrapTranslatableModel("base.FooterText"),
    ]
