# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20170303_0829'),
        ('base', '0016_merge_20170304_0053'),
    ]

    operations = [
    ]
