# Generated by Django 6.0.dev20250116121251 on 2025-01-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_remove_genericsettings_twitter_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "person", "verbose_name_plural": "people"},
        ),
    ]
