# Generated by Django 5.2.3 on 2025-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_alter_formpage_body_alter_gallerypage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="featured_section_1_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the featured section 1",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="featured_section_2_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the featured section 2",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="featured_section_3_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the featured section 3",
                max_length=255,
            ),
        ),
    ]
