# Generated by Django 5.2.9 on 2026-01-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_formpage_body_alter_gallerypage_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='promo_image',
            new_name='lead_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='promo_text',
            new_name='lead_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='promo_title',
            new_name='lead_title',
        ),
    ]
