# Generated by Django 6.0.2 on 2026-03-06 22:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_footermenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermenu',
            name='sections',
            field=wagtail.fields.StreamField([('section', 11)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 2)]], {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('document', 4)]], {}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('url', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('page', 3), ('document', 5), ('external_url', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('title', 1), ('link', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 10)]], {})}),
        ),
    ]
