# Generated by Django 6.0.7 on 2026-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0027_rename_promo_image_homepage_lead_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="introduction",
            field=models.TextField(blank=True, help_text="Text to describe the page"),
        ),
    ]
