# Generated by Django 6.0.3 on 2026-03-13 09:41

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_promo_image_homepage_lead_image_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('name', models.CharField(max_length=255)),
                ('sections', wagtail.fields.StreamField([('section', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional. If left blank, the linked page's title will be used.", 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 5: ('wagtail.blocks.StreamBlock', [[('page', 2), ('external_url', 3), ('document', 4)]], {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('title', 1), ('link', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 7)]], {})})),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'verbose_name': 'footer menu',
                'verbose_name_plural': 'footer menus',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
