# Generated by Django 3.1 on 2020-08-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_auto_20180522_1856"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="clean_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Safe name of the form field, the label converted to ascii_snake_case",
                max_length=255,
                verbose_name="name",
            ),
        ),
    ]
