# Generated by Django 3.2.15 on 2022-09-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_use_json_field_for_body_streamfield"),
        ("wagtailimages", "0024_index_image_file_hash"),
        ("base", "0009_alter_homepage_promo_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="People",
            new_name="Person",
        ),
    ]
