# Generated by Django 5.1.dev20240316121317 on 2024-04-23 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_userapprovaltask"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footertext",
            options={
                "verbose_name": "footer text",
                "verbose_name_plural": "footer text",
            },
        ),
    ]
